### PR TITLE
Update dependencies & cleanup code

### PR DESCRIPTION
**Pull request by uku3lig**
This PR bumps all rust dependencies and all fabric toolchain dependencies (minecraft version is still 1.18.1)

Most clippy warnings have been fixed (only 3 remain, which are things that probably *shouldn't* be removed) and most java warnings have been fixed.

### CODE REVIEW

**Review by birbe — APPROVED** [review]
lgtm

**Review by Batku — APPROVED** [review]
lgtm :)

**Review by DasBlackfur — APPROVED** [review]
lgtm

**Review by MunirG05 — APPROVED** [review]
LGTM!

**Review by The-Minecraft-Scientist — APPROVED** [review]
lgtm!

**Review by cohaereo — APPROVED** [review]
lgtm!

**Review by D720-I-harcma-rortti — APPROVED** [review]
Yes lgtm

**Review by Ultrasonic1209 — APPROVED** [review]
lgtm :)

**Review by lucsoft — APPROVED** [review]
lgtm :shipit:

**Review by OakleyCord — APPROVED** [review]
lgtm

**Review by Dworv — APPROVED** [review]
lgtm

**Review by accusitive — APPROVED** [review]
lgtm

**Review by eminarican — APPROVED** [review]
lgtm :p

**Review by FlashOnFire — APPROVED** [review]
Lgtm !

**Review by Spider-earth — COMMENTED** [review]
ltgm

**Pull request merged**
